on: [push]

name: lint

jobs:
  lint:
    runs-on: [ubuntu-20.04]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_cran("lintr")
        shell: Rscript {0}
      - name: Lint
        run: lintr::lint_dir('./code')
        shell: Rscript {0}
