on: [push]

name: lint

jobs:
  lint:
    runs-on: [ubuntu-20.04]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libxml2-dev
          R -e 'install.packages("lintr")' 
      - name: Lint
        run: R -e 'lintr::lint_dir("./code")'